{%- if pillar.glance.server is defined %}
[logstreamer_glance]
type = "LogstreamerInput"
log_directory = "/var/log/glance"
file_match = 'glance-registry\.log\.?(?P<Index>\d+)?(.gz)?'
priority = ["^Index"]
decoder = "glance"

[glance]
type = "SandboxDecoder"
filename = "lua_modules/decoders/openstack.lua"
module_directory = "/usr/share/heka/lua_modules;/usr/share/heka/lua_modules/common"
{% endif %}
